baseURL: https://www.kodesiana.com/

title: Kodesiana
timeZone: Asia/Jakarta
enableGitInfo: false

languageCode: id
defaultContentLanguage: id
hasCJKLanguage: false

paginate: 5
summaryLength: 80
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

permalinks:
  post: "/:section/:slug/"

ignoreFiles:
  - \.bin
  - \.cache
  - \.play
  - \.vscode
  - node_modules
  - public

taxonomies:
  tag: tags
  series: series
  categories: categories

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - name: Beranda
      url: /
      weight: 1
    - name: Arsip
      url: /archives
      weight: 2
    - name: Cari
      url: /search
      weight: 3
    - url: /projects
      name: Proyek
      weight: 4
    - url: /privacy-policy
      name: Privasi
      weight: 5
    - name: Tentang
      url: /about
      weight: 6

params:
  # blog metadata
  title: Kodesiana
  author: Fahmi Noor Fiqri
  description: "#NgodingItuMudah"
  keywords:
    - kodesiana
    - programming
    - C#
    - devops
    - machine learning
    - artificial intelligence
  images:
    - /img/logo.png

  logo:
    text: "Kodesiana"
    icon: /img/favicon/favicon-32x32.png
    iconHeight: 32

  homeInfoParams:
    Title: "Hai, aku Fahmi\U0001F44B"
    Content: "**#NgodingItuMudah** Yuk kita belajar belajar pemrograman, DevOps, dan *machine learning*"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  tocOpen: false
  comments: true
  dateFormat: "2 January 2006"

  socialIcons:
    - name: tabler:cash-banknote
      url: https://saweria.co/fahminlb33
    - name: tabler:brand-youtube
      url: https://www.youtube.com/c/FahmiNoorFiqri
    - name: tabler:brand-github
      url: "https://github.com/fahminlb33"
    - name: tabler:brand-linkedin
      url: "https://www.linkedin.com/in/fahmi-noor-fiqri"
    - name: tabler:brand-stackoverflow
      url: "https://stackoverflow.com/users/5561144/fahmi-noor-fiqri"
    - name: tabler:brand-instagram
      url: "https://instagram.com/fahminoorfiqri"
    - name: tabler:brand-twitter
      url: "https://twitter.com/fahminoorfiqri"

  integrations:
    googleAdsense: "6850104426944295"
    googleAnalytics: "G-WCSBJTCX6E"
    googleSiteVerification: "orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M"
    microsoftBing: ""
    microsoftClarity: "54zpth9y8i"
